#!/bin/bash

COL_NORM=$'\033[39m'
COL_RED=$'\033[31m'
COL_GREEN=$'\033[32m'
COL_CYAN=$'\033[36m'

if [ $# -lt 1 ] ; then
        echo "${COL_GREEN}Usage: parse google docs spreadsheet content using 'restatic source_folder target_folder' ${COL_NORM}"
        echo 
        echo "By Binaryage.com, for more info see projects homepage"
        exit 1
fi

echo "${COL_RED} Restatic started parsing html files from $1 to $2. ${COL_NORM}"

if [ -d $1 ]
then
	if [ -d $1 ]
	then
		php parser.php $1 $2
	else
		echo "Target dir doesnt exists."
	fi
else
 echo "Source dir doesnt exists."
fi